language: python
python: 2.7
env:
  - TOXENV=py27
install:
  - pip install -U tox
script: tox
notifications:
  irc:
    use_notice: true
    skip_join: true
    channels:
      - irc.freenode.org#scrapy
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: scrapy
  password:
    secure:
  on:
    tags: true
    all_branches: true
    repo: scrapy/scrapy-djangoitem
    condition: "$TOXENV == py27"
